services:
  rapbot:
    build: .
    container_name: rapbot
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # persist the SQLite DB and any uploads
      - rapbot_data:/app/backend/instance
    restart: unless-stopped

volumes:
  rapbot_data:

